"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "app/bottle-orientation-panel-integration.js"), "utf8");
const recovery = fs.readFileSync(path.join(root, "app/bottle-orientation-panel-recovery-integration.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const serviceWorker = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const animationRuntime = fs.readFileSync(path.join(root, "app/animation-runtime.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));

assert.match(source, /Bottle Orientation &amp; Wipe Visual/);
assert.match(source, /Full servo cycle/);
assert.match(source, /Play Full Cycle/);
assert.match(source, /Full program path/);
assert.match(source, /fullCycleVisualV76: true/);
assert.match(source, /clearLongNeckBottleV76: true/);
assert.match(source, /referenceBottleProfileV77: true/);
assert.match(source, /cylindricalLabelProjectionV77: true/);
assert.match(source, /leadingEdgeBodyBackVisualV77: true/);
assert.match(source, /mainAnimationSyncV77: true/);
assert.match(source, /machineDirectionVisualV78: true/);
assert.match(source, /directionAwareDegreeMarkersV78: true/);
assert.match(source, /rightFrontZeroDatumV79: true/);
assert.match(source, /oppositeCarouselBottleSpinV79: true/);
assert.match(source, /pseudo3dBottleSideViewV81: true/);
assert.match(source, /curvedWrappedLabelBandV81: true/);
assert.match(source, /orientationDepthCueV81: true/);
assert.match(source, /selectedMockupBottleV82: true/);
assert.match(source, /sideViewOrientationFloorV82: true/);
assert.match(source, /sideViewDegreeRingV82: true/);
assert.match(source, /liveBaseAngleMarkerV82: true/);
assert.match(source, /elevatedThreeQuarterBottleV83: true/);
assert.match(source, /liveLongitudinalDatumCueV83: true/);
assert.match(source, /visibleTopNeckDiscV83: true/);
assert.match(source, /perspectiveBaseEllipseV83: true/);
assert.match(source, /data-three-quarter-camera=\"true\"/);
assert.match(source, /3D PERSPECTIVE/);
assert.match(source, /perspectiveDatumX/);
assert.match(source, /neckPointerX/);
assert.match(source, /data-side-orientation-floor=\"true\"/);
assert.match(source, /orientationRingPoint/);
assert.match(source, /orientationMarker/);
assert.match(source, /\[0,90,180,270\]\.map/);
assert.match(source, /data-pseudo-3d-bottle=\"true\"/);
assert.match(source, /data-pseudo-3d-label=\"true\"/);
assert.match(source, /wrappedBandSegmentPath/);
assert.match(source, /DATUM FRONT/);
assert.match(source, /x: cx \+ Math\.cos\(radians\) \* radius/);
assert.match(source, /y: cy \+ Math\.sin\(radians\) \* radius/);
assert.match(source, /span > 180 \? 1 : 0} 1/);
assert.match(recovery, /nativeBottleDatumCompatibilityV79: true/);
assert.match(source, /function machineVisualAngle/);
assert.match(source, /runtimeState\(\)\?\.direction/);
assert.match(source, /function tableFrameVisualAngle/);
assert.match(source, /angleToSvgRotation\(normalizeAngle\(tableAngle\)\)/);
assert.match(source, /function headOneWorldVisualAngle/);
assert.match(source, /return tableFrameVisualAngle\(tableAngle\) \+ machineVisualAngle\(plateAngle\)/);
assert.match(source, /markerAngle = tableFrameAngle \+ machineVisualAngle\(degree\)/);
assert.match(source, /data-top-view-frame=\"head-1-world\"/);
assert.match(source, /headOneWorldFrameTopViewV80: true/);
assert.match(source, /mechanicalMapTransformParityV80: true/);
assert.match(source, /visualPlateAngle = machineVisualAngle\(plateAngle\)/);
assert.match(source, /projectLabelArcSegments/);
assert.match(source, /data-wrapped-label=\"true\"/);
assert.match(source, /section === \"body\" \|\| section === \"back\"/);
assert.match(source, /coverage\.tackMode = \"leading\"/);
assert.match(source, /LEADING EDGE/);
assert.match(animationRuntime, /LabelerBottleOrientationPanel\?\.renderAll\?\.\(\)/);
assert.match(source, /fullProgramPath: stationOnePath/);
assert.match(source, /__orientationTableStart/);
assert.doesNotMatch(source, /rowStart > start \+ 150/);
assert.match(source, /wipeDownTelemetry/);
assert.match(source, /telemetry\?\.station/);
assert.match(source, /wipeStationContextAtAngle/);
assert.match(source, /Pseudo-3D clear glass bottle side view|Elevated three-quarter clear glass bottle perspective/);
assert.match(source, /data-pseudo-3d-glass=\"true\"/);
assert.match(source, /stop-color="#e8f4f8"/);
assert.match(source, /stop-opacity="\.46"/);
assert.match(source, /neckBase\+3/);
assert.match(source, /programForSource\(source\)/);
assert.match(source, /source === "simulation"/);
assert.match(source, /return generatedProgram\(\)/);
assert.match(source, /selectedLabelSpec/);
assert.match(source, /selectedBottleSpec/);
assert.match(source, /bodyCircumference/);
assert.match(source, /degFromMm/);
assert.match(source, /\[0,90,180,270\]/);
assert.match(source, /TOP VIEW/);
assert.match(source, /SIDE VIEW|3D PERSPECTIVE/);
assert.match(source, /data-orientation-scrubber/);
assert.match(source, /wrapRenderer\("renderProgram", "program"\)/);
assert.match(source, /wrapRenderer\("renderSimulation", "simulation"\)/);
assert.match(source, /programAccessibleWithoutSimulationV72/);
assert.match(bootstrap, /three\-quarter\-perspective\-bottle\-v83\-20260811\-1908/);
assert.match(serviceWorker, /three\-quarter\-perspective\-bottle\-v83\-20260811\-1908/);
assert.equal(manifest.buildId, "three-quarter-perspective-bottle-v83-20260811-1908");
console.log("Three-quarter perspective bottle v83 regression passed.");
