"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const recovery=fs.readFileSync(path.join(root,"app/bottle-orientation-panel-recovery-integration.js"),"utf8");
const panel=fs.readFileSync(path.join(root,"app/bottle-orientation-panel-integration.js"),"utf8");
const bootstrap=fs.readFileSync(path.join(root,"app/bootstrap.js"),"utf8");
const manifest=JSON.parse(fs.readFileSync(path.join(root,"update-manifest.json"),"utf8"));
assert.match(panel,/topViewOnlyV84: true/);
assert.doesNotMatch(panel,/data-orientation-side/);
assert.doesNotMatch(panel,/>WIPE<\/text>/);
assert.match(recovery,/const VERSION = 4/);
assert.match(recovery,/observeDocument/);
assert.match(recovery,/observeHost\(source\);\n      recoverSource\(source\);/);
assert.match(recovery,/existing\?\.host === host/);
assert.match(recovery,/observers\.set\(source, \{ host, observer \}\)/);
assert.match(recovery,/persistentTopViewMountV85: true/);
assert.match(recovery,/workspaceHostReacquireV85: true/);
assert.match(bootstrap,/map-machine-settings-wipe-direction-v87-20260811-1940/);
assert.equal(manifest.buildId,"map-machine-settings-wipe-direction-v87-20260811-1940");
console.log("Bottle Orientation top-view mount recovery v85 regression passed.");
