"use strict";

const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const source=fs.readFileSync(path.join(root,"app/bottle-orientation-panel-integration.js"),"utf8");
const recovery=fs.readFileSync(path.join(root,"app/bottle-orientation-panel-recovery-integration.js"),"utf8");
const bootstrap=fs.readFileSync(path.join(root,"app/bootstrap.js"),"utf8");
const serviceWorker=fs.readFileSync(path.join(root,"service-worker.js"),"utf8");
const animationRuntime=fs.readFileSync(path.join(root,"app/animation-runtime.js"),"utf8");
const manifest=JSON.parse(fs.readFileSync(path.join(root,"update-manifest.json"),"utf8"));
assert.match(source,/Bottle Orientation<\/strong>/);
assert.match(source,/synchronized to labeler animation/);
assert.match(source,/data-orientation-top/);
assert.doesNotMatch(source,/data-orientation-side/);
assert.doesNotMatch(source,/function sideViewSvg/);
assert.doesNotMatch(source,/\n\s*sideViewSvg,/);
assert.match(source,/staleSideViewExportRemovedV86: true/);
assert.doesNotMatch(source,/>WIPE<\/text>/);
assert.match(source,/TOP VIEW/);
assert.match(source,/data-top-view-frame=\"head-1-world\"/);
assert.match(source,/headOneWorldFrameTopViewV80: true/);
assert.match(source,/mechanicalMapTransformParityV80: true/);
assert.match(source,/coverage\.tackMode = \"leading\"/);
assert.match(animationRuntime,/LabelerBottleOrientationPanel\?\.renderAll\?\.\(\)/);
assert.match(source,/topViewOnlyV84: true/);
assert.match(source,/standaloneOrientationControlsRemovedV84: true/);
assert.match(source,/topViewWipeGraphicRemovedV84: true/);
assert.match(source,/mainAnimationOnlyV84: true/);
const markup=source.match(/function panelMarkup\(source\) \{([\s\S]*?)\n  \}/)?.[1]||"";
assert.doesNotMatch(markup,/bottle-orientation-controls/);
assert.doesNotMatch(markup,/data-orientation-scrubber/);
assert.doesNotMatch(markup,/data-orientation-speed/);
assert.doesNotMatch(markup,/data-orientation-action-button/);
assert.match(recovery,/nativeBottleDatumCompatibilityV79: true/);
assert.match(bootstrap,/brand-selection-event-authority-v94-20260811-2150/);
assert.match(serviceWorker,/brand-selection-event-authority-v94-20260811-2150/);
assert.equal(manifest.buildId,"brand-selection-event-authority-v94-20260811-2150");
console.log("Top-view-only Bottle Orientation baseline regression passed.");
