"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "app/bottle-orientation-panel-integration.js"), "utf8");
const recovery = fs.readFileSync(path.join(root, "app/bottle-orientation-panel-recovery-integration.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const serviceWorker = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const animationRuntime = fs.readFileSync(path.join(root, "app/animation-runtime.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));

assert.match(source, /Bottle Orientation &amp; Wipe Visual/);
assert.match(source, /Full servo cycle/);
assert.match(source, /Play Full Cycle/);
assert.match(source, /Full program path/);
assert.match(source, /fullCycleVisualV76: true/);
assert.match(source, /clearLongNeckBottleV76: true/);
assert.match(source, /referenceBottleProfileV77: true/);
assert.match(source, /cylindricalLabelProjectionV77: true/);
assert.match(source, /leadingEdgeBodyBackVisualV77: true/);
assert.match(source, /mainAnimationSyncV77: true/);
assert.match(source, /machineDirectionVisualV78: true/);
assert.match(source, /directionAwareDegreeMarkersV78: true/);
assert.match(source, /rightFrontZeroDatumV79: true/);
assert.match(source, /oppositeCarouselBottleSpinV79: true/);
assert.match(source, /x: cx \+ Math\.cos\(radians\) \* radius/);
assert.match(source, /y: cy \+ Math\.sin\(radians\) \* radius/);
assert.match(source, /span > 180 \? 1 : 0} 1/);
assert.match(recovery, /nativeBottleDatumCompatibilityV79: true/);
assert.match(source, /function machineVisualAngle/);
assert.match(source, /runtimeState\(\)\?\.direction/);
assert.match(source, /markerAngle = machineVisualAngle\(degree\)/);
assert.match(source, /visualPlateAngle = machineVisualAngle\(plateAngle\)/);
assert.match(source, /projectLabelArcSegments/);
assert.match(source, /data-wrapped-label=\"true\"/);
assert.match(source, /section === \"body\" \|\| section === \"back\"/);
assert.match(source, /coverage\.tackMode = \"leading\"/);
assert.match(source, /LEADING EDGE/);
assert.match(animationRuntime, /LabelerBottleOrientationPanel\?\.renderAll\?\.\(\)/);
assert.match(source, /fullProgramPath: stationOnePath/);
assert.match(source, /__orientationTableStart/);
assert.doesNotMatch(source, /rowStart > start \+ 150/);
assert.match(source, /wipeDownTelemetry/);
assert.match(source, /telemetry\?\.station/);
assert.match(source, /wipeStationContextAtAngle/);
assert.match(source, /Reference-style clear glass bottle side view/);
assert.match(source, /stop-color="#dce9ef"/);
assert.match(source, /stop-opacity="\.25"/);
assert.match(source, /neckBase\+3/);
assert.match(source, /programForSource\(source\)/);
assert.match(source, /source === "simulation"/);
assert.match(source, /return generatedProgram\(\)/);
assert.match(source, /selectedLabelSpec/);
assert.match(source, /selectedBottleSpec/);
assert.match(source, /bodyCircumference/);
assert.match(source, /degFromMm/);
assert.match(source, /\[0,90,180,270\]/);
assert.match(source, /TOP VIEW/);
assert.match(source, /SIDE VIEW/);
assert.match(source, /data-orientation-scrubber/);
assert.match(source, /wrapRenderer\("renderProgram", "program"\)/);
assert.match(source, /wrapRenderer\("renderSimulation", "simulation"\)/);
assert.match(source, /programAccessibleWithoutSimulationV72/);
assert.match(bootstrap, /machine-bottle-datum-alignment-v79-20260811-1756/);
assert.match(serviceWorker, /machine-bottle-datum-alignment-v79-20260811-1756/);
assert.equal(manifest.buildId, "machine-bottle-datum-alignment-v79-20260811-1756");
console.log("Machine bottle datum alignment v79 regression passed.");
