"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "public-ratings-v96-20260812-1821";
const feedback = fs.readFileSync(path.join(root, "app/feedback-center-integration.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
assert.match(feedback, /servoforge-feedback-access-token-v1/);
assert.match(feedback, /feedbackCenterButton/);
assert.match(feedback, /New Request/);
assert.match(feedback, /My Requests/);
assert.match(feedback, /Support Admin/);
assert.match(feedback, /ratingStars/);
assert.match(feedback, /appContext/);
assert.match(feedback, /adminReply/);
assert.match(bootstrap, /app\/feedback-center-integration\.js/);
assert.match(sw, /app\/feedback-center-integration\.js/);
for (const source of [bootstrap, sw, updater, index, app]) assert.match(source, new RegExp(BUILD));
assert.equal(manifest.buildId, BUILD);
assert.doesNotMatch(feedback, /SUPABASE_SERVICE_ROLE_KEY|service_role/i, "Privileged Supabase credentials must never be shipped to the browser.");
console.log("Anonymous Feedback Center v95 regression passed.");
