"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const layout = fs.readFileSync(path.join(root, "app/map-workspace-compact-support-integration.js"), "utf8");
const recovery = fs.readFileSync(path.join(root, "app/bottle-orientation-panel-recovery-integration.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
assert.match(layout, /map-support-panels/);
assert.match(layout, /appendChild\(overlays\)/);
assert.match(layout, /appendChild\(wipeDown\)/);
assert.match(layout, /48vh/);
assert.match(layout, /480px/);
assert.match(recovery, /data-bottle-orientation-panel/);
assert.match(recovery, /MutationObserver/);
assert.match(recovery, /recoverSource/);
assert.match(bootstrap, /map-workspace-compact-support-integration\.js/);
assert.match(bootstrap, /bottle-orientation-panel-recovery-integration\.js/);
assert.match(bootstrap, /map-layout-dead-zone-bottle-visual-v75-20260811-1628/);
assert.match(index, /build=map-layout-dead-zone-bottle-visual-v75-20260811-1628/);
console.log("Map workspace and Bottle Orientation v75 regression passed.");
