"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const events=fs.readFileSync(path.join(root,"app/controllers/map-builder-event-controller.js"),"utf8");
const controller=fs.readFileSync(path.join(root,"app/map-builder-controller.js"),"utf8");
const catalog=fs.readFileSync(path.join(root,"app/company-default-map-catalog-integration.js"),"utf8");
const loader=fs.readFileSync(path.join(root,"app/wipe-down-builder.js"),"utf8");
assert.match(events,/machineSettingFields = new Set/);
assert.match(events,/if \(machineSettingFields\.has\(target\.id\)\) return/);
assert.match(events,/saveMapDefinitionFromControls\(\{ type: eventType \}\)/);
assert.match(events,/machineSettingsCommitOnChangeV87: true/);
assert.match(controller,/function machineSettingNumber/);
assert.match(controller,/map\.localMachineSettingsOverride = true/);
assert.match(catalog,/local\?\.localMachineSettingsOverride/);
assert.match(catalog,/machineSettings: clone\(local\.machineSettings/);
assert.match(loader,/0\.9\.10-map-machine-settings-v87/);
console.log("Map machine settings editability v87 regression passed.");
