"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "public-ratings-v96-20260812-1821";
const source = fs.readFileSync(path.join(root, "app/feedback-center-integration.js"), "utf8");
assert.match(source, /servoforge-ratings/);
assert.match(source, /data-feedback-tab="ratings">Ratings</);
assert.match(source, /data-feedback-pane="ratings"/);
assert.match(source, /maxlength="200"/);
assert.match(source, /servoforgeRatingCounter/);
assert.match(source, /loadRatings/);
assert.match(source, /submitPublicRating/);
assert.match(source, /Update Rating/);
assert.match(source, /Your rating/);
assert.doesNotMatch(source, /SUPABASE_SERVICE_ROLE_KEY|service_role/i);
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
for (const delivery of [bootstrap, sw, updater, app, index]) assert.match(delivery, new RegExp(BUILD));
console.log("Public Ratings v96 regression passed.");
