"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.resolve(__dirname, "..");
const tabs = fs.readFileSync(path.join(root, "app/controllers/tabs-controller.js"), "utf8");
const setup = fs.readFileSync(path.join(root, "app/setup-bindings.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
assert.doesNotThrow(() => new vm.Script(tabs));
assert.match(tabs, /navigationCaptureV3:\s*true/);
assert.match(tabs, /setDirectTabState/);
assert.match(tabs, /stopImmediatePropagation/);
assert.doesNotMatch(setup, /addEventListener\s*\(/, "setup-bindings must not compete with TabsController");
assert.match(setup, /workspaceNavigationOwner:\s*"LabelerTabsController"/);
assert.doesNotMatch(bootstrap, /"app\/controllers\/tabs-controller\.js"/);
const navIndex = index.indexOf("app/controllers/tabs-controller.js");
const setupIndex = index.indexOf("app/setup-bindings.js");
const bootstrapIndex = index.indexOf("app/bootstrap.js");
assert.ok(navIndex >= 0 && navIndex < setupIndex && setupIndex < bootstrapIndex);
console.log("Authoritative top navigation recovery regression passed.");
