"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const build = "wipe-runtime-delivery-v90-20260811-2020";
const update = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const feature = fs.readFileSync(path.join(root, "app/simulation-collapsible-integration.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
assert.match(update, /loadStagingFeatureModules[\s\S]*const BUILD_ID = "wipe-runtime-delivery-v90-20260811-2020"/);
assert.match(update, /script\.src = `\.\/\$\{path\}\?v=\$\{RELEASE_VERSION\}&build=\$\{encodeURIComponent\(BUILD_ID\)\}`/);
assert.match(feature, /wipe-telemetry-service\.js\?v=0\.9\.10-wipe-direction-v90/);
assert.match(feature, /wipe-telemetry-renderer\.js\?v=0\.9\.10-wipe-direction-v90/);
for (const source of [index, app, bootstrap, sw]) assert.ok(source.includes(build), "top-level delivery point must carry v90 build id");
assert.equal(manifest.buildId, build);
console.log("Wipe runtime delivery v90 regression passed.");
