"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const source = fs.readFileSync(path.resolve(__dirname, "../app/wipe-telemetry-service.js"), "utf8");
const start = source.indexOf("function liveWipeMachineDirection()");
const end = source.indexOf("function wipeVisualApplication", start);
assert.ok(start >= 0 && end > start);
const fn = source.slice(start, end);
const semanticIndex = fn.indexOf('document.getElementById("mapDirection")');
const mapIndex = fn.indexOf("activeMachineMap");
const runtimeIndex = fn.indexOf("const runtime = String(state.direction");
assert.ok(semanticIndex >= 0 && mapIndex >= 0 && runtimeIndex >= 0);
assert.ok(semanticIndex < mapIndex && mapIndex < runtimeIndex, "semantic UI/map direction must precede internal runtime convention");
assert.match(source, /semanticMachineDirectionV89: true/);
console.log("Wipe direction compatibility regression passed under v89 semantic parity.");
