"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "workspace-selection-delivery-v91-20260811-2033";
const persistence = fs.readFileSync(path.join(root, "app/persistence.js"), "utf8");
assert.match(persistence, /"wipeBuilderOpen", "activeTab", "activeMapId"/);
assert.match(persistence, /activeTab:\s*state\.activeTab/);
const actions = fs.readFileSync(path.join(root, "app/controllers/workspace-action-service.js"), "utf8");
assert.match(actions, /function activeWorkspaceTab\(/);
assert.match(actions, /restoreWorkspaceTab\(tabBefore\)/);
assert.match(actions, /options\.beforeRender/);
const build = fs.readFileSync(path.join(root, "app/controllers/build-inputs-controller.js"), "utf8");
assert.match(build, /const requestedBrand = String\(selected\.brand\)/);
assert.match(build, /state\.selectedBrand = requestedBrand/);
assert.match(build, /actions\.call\("saveCurrentSettings"\)/);
const startup = fs.readFileSync(path.join(root, "app/startup-runtime.js"), "utf8");
assert.match(startup, /LabelerTabsController\?\.setDirectTabState/);
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
assert.match(updater, new RegExp(BUILD));
assert.match(updater, /destination\.pathname\.endsWith\("\/"\)/);
assert.doesNotMatch(updater, /pathname\.endsWith\(`\/\$\{path\}`\)/);
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
assert.match(app, new RegExp(BUILD));
assert.match(app, /script\.src === expected/);
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
assert.match(bootstrap, new RegExp(BUILD));
assert.match(sw, new RegExp(BUILD));
assert.match(index, new RegExp(BUILD));
assert.equal(manifest.buildId, BUILD);
assert.equal(manifest.releaseUrl, "https://bry4nt06.github.io/labeler-tool-staging/index.html");
console.log("Workspace selection and update delivery v91 regression passed.");
