"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "anonymous-feedback-center-v95-20260812-1755";
const guidance = fs.readFileSync(path.join(root, "app/controllers/specification-sensor-guidance-controller.js"), "utf8");
const setup = fs.readFileSync(path.join(root, "app/controllers/setup-event-controller-integration.js"), "utf8");
assert.match(guidance, /brandSelectionOwnedByBuildInputsV94:\s*true/);
assert.match(setup, /brandSelectionAuthorityV94:\s*true/);
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
for (const source of [bootstrap, sw, updater, app, index]) assert.match(source, new RegExp(BUILD));
assert.equal(manifest.buildId, BUILD);
console.log("Brand selection event authority and delivery v94 regression passed.");
