"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "brand-selection-transaction-v92-20260811-2109";
const persistence = fs.readFileSync(path.join(root, "app/persistence.js"), "utf8");
assert.match(persistence, /"wipeBuilderOpen", "activeTab", "activeMapId"/);
assert.match(persistence, /activeTab:\s*state\.activeTab/);
const actions = fs.readFileSync(path.join(root, "app/controllers/workspace-action-service.js"), "utf8");
assert.match(actions, /typeof options\.restoreTab === "string"/);
assert.match(actions, /restoreWorkspaceTab\(tabBefore\)/);
const build = fs.readFileSync(path.join(root, "app/controllers/build-inputs-controller.js"), "utf8");
assert.match(build, /restoreTab:\s*"buildInputs"/);
assert.match(build, /brandSelectionSequence/);
assert.match(build, /requestAnimationFrame/);
const setup = fs.readFileSync(path.join(root, "app/setup-bindings.js"), "utf8");
assert.doesNotMatch(setup, /addEventListener\s*\(/);
assert.match(setup, /workspaceNavigationOwner:\s*"LabelerTabsController"/);
const delegated = fs.readFileSync(path.join(root, "app/controllers/setup-event-controller-integration.js"), "utf8");
assert.match(delegated, /target\.id === "brandSelect"/);
assert.match(delegated, /setDirectTabState\?\.\("buildInputs"/);
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
assert.match(bootstrap, /script\.src === expected/);
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
assert.match(sw, /url\.searchParams\.has\("build"\)/);
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
for (const source of [bootstrap, sw, updater, app, index]) assert.match(source, new RegExp(BUILD));
assert.equal(manifest.buildId, BUILD);
console.log("Brand selection transaction and delivery v92 regression passed.");
