"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const BUILD = "brand-selection-presentation-v93-20260811-2124";
const actions = fs.readFileSync(path.join(root, "app/controllers/workspace-action-service.js"), "utf8");
assert.match(actions, /function presentCurrentState\(/);
assert.match(actions, /coordinator\.driver\.present\(coordinator\.handlers\(\)\)/);
assert.doesNotMatch(actions.match(/function presentCurrentState\([\s\S]*?
  \}/)?.[0] || "", /call\("render"\)/);
const build = fs.readFileSync(path.join(root, "app/controllers/build-inputs-controller.js"), "utf8");
assert.match(build, /render:\s*null/);
assert.match(build, /actions\.present\?\.\(\)/);
assert.match(build, /presentRequestedSelection/);
assert.match(build, /restoreTab:\s*"buildInputs"/);
const bootstrap = fs.readFileSync(path.join(root, "app/bootstrap.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
const updater = fs.readFileSync(path.join(root, "app/update-manager.js"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "update-manifest.json"), "utf8"));
for (const source of [bootstrap, sw, updater, app, index]) assert.match(source, new RegExp(BUILD));
assert.equal(manifest.buildId, BUILD);
console.log("Brand selection presentation and delivery v93 regression passed.");
